### ISSUE TITLE
firefox更新89后 叉按鈕（delete）變窄了

### ISSUE THREAD

**Issue by taoy4869** [sakuyaa/readLater#2]
88是方形的，89是長方形的
https://img56.pixhost.to/images/89/214614267_snipaste_2021-06-13_16-53-35.png
https://img56.pixhost.to/images/89/214614264_snipaste_2021-06-13_16-25-13.png

**Comment by sakuyaa** [comment]
因为89更新了浏览器的css导致外观变了，新版本已经解决了
